name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gpg
        run: sudo apt-get install python3-gpg
      - name: Run tests
        run: |
          cd tests/
          git clone https://github.com/toddfratello/pyomcore.git
          pip3 install ./pyomcore
          pip3 install ..
          ./test_pyomcash.py ./tmp https://github.com/toddfratello/pyomcore.git https://github.com/toddfratello/pyomcash.git
